// web/src/pages/ResetPassword.tsx
import { useState } from "react";

export default function ResetPassword() {
  const [formData, setFormData] = useState({
    newPassword: "",
    confirmPassword: "",
  });
  const [isLoading, setIsLoading] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    setIsLoading(true);

    setTimeout(function () {
      // Simulating API call

      setIsLoading(false);
      setFormData({ newPassword: "", confirmPassword: "" });
    }, 1000);

    // await api call to send reset password link
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100 p-4">
      <div className="w-full max-w-md rounded-xl bg-white p-8 shadow-lg">
        <h2 className="mb-2 text-center text-2xl font-bold text-gray-900">
          Reset your password
        </h2>
        <p className="mb-6 text-center text-sm text-gray-600">
          Enter a new password below to change your password
        </p>

        <form className="space-y-4" onSubmit={handleSubmit}>
          <div>
            <label
              htmlFor="newPassword"
              className="mb-1 block text-sm font-medium text-gray-700"
            >
              New Password
            </label>
            <input
              type="password"
              id="newPassword"
              name="newPassword"
              value={formData.newPassword}
              onChange={handleChange}
              className="w-full rounded-lg border border-gray-300 px-4 py-2 outline-none transition-all focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
              placeholder="••••••••"
            />
          </div>

          <div>
            <label
              htmlFor="confirmPassword"
              className="mb-1 block text-sm font-medium text-gray-700"
            >
              Password
            </label>
            <input
              type="password"
              id="confirmPassword"
              name="confirmPassword"
              value={formData.confirmPassword}
              onChange={handleChange}
              className="w-full rounded-lg border border-gray-300 px-4 py-2 outline-none transition-all focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
              placeholder="••••••••"
            />
          </div>

          <button
            type="submit"
            disabled={isLoading} // Disable button during loading
            className={`w-full rounded-lg py-2.5 font-medium text-white transition-colors ${
              isLoading
                ? "cursor-not-allowed bg-indigo-400"
                : "bg-indigo-600 hover:bg-indigo-700"
            }`}
          >
            {isLoading ? "Loading..." : "Change Password"}
          </button>
        </form>
      </div>
    </div>
  );
}

// web/src/routes/(auth)/reset-password/+page.svelte
<script lang="ts">
	let formData = { newPassword: '', confirmPassword: '' };
	let isLoading = false;

	const handleSubmit = (_: SubmitEvent) => {
		isLoading = true;

		setTimeout(() => {
			isLoading = false;
			formData = { newPassword: '', confirmPassword: '' }; // Reset form
		}, 1000);
	};
</script>

<h2 class="mb-2 text-center text-2xl font-bold text-gray-900">Reset your password</h2>
<p class="mb-6 text-center text-sm text-gray-600">
	Enter a new password below to change your password
</p>

<form class="space-y-4" on:submit|preventDefault={handleSubmit}>
	<div>
		<label for="newPassword" class="mb-1 block text-sm font-medium text-gray-700">
			New Password
		</label>
		<input
			type="password"
			id="newPassword"
			name="newPassword"
			bind:value={formData.newPassword}
			class="w-full rounded-lg border border-gray-300 px-4 py-2 transition-all outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
			placeholder="••••••••"
			required
		/>
	</div>

	<div>
		<label for="confirmPassword" class="mb-1 block text-sm font-medium text-gray-700">
			Confirm Password
		</label>
		<input
			type="password"
			id="confirmPassword"
			name="confirmPassword"
			bind:value={formData.confirmPassword}
			class="w-full rounded-lg border border-gray-300 px-4 py-2 transition-all outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
			placeholder="••••••••"
			required
		/>
	</div>

	<button
		type="submit"
		class="w-full rounded-lg py-2.5 font-medium text-white transition-colors {isLoading
			? 'cursor-not-allowed bg-indigo-400'
			: 'bg-indigo-600 hover:bg-indigo-700'}"
		disabled={isLoading}
	>
		{isLoading ? 'Loading...' : 'Change Password'}
	</button>
</form>

<div class="mt-6 text-center text-sm text-gray-600">
	Remember your password?
	<a href="/login" class="font-medium text-indigo-600 hover:text-indigo-500"> Sign In </a>
</div>
