// web/src/components/Header.tsx
import { useState } from "react";
import { MagnifyingGlassIcon, Bars3Icon } from "@heroicons/react/24/solid";

const Header: React.FC = () => {
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);

  const toggleDropdown = () => {
    setIsDropdownOpen((prev) => !prev);
  };

  return (
    <header className="shadow-bottom sticky top-0 z-20 lg:ml-64 h-16 bg-white">
      <div className="container mx-auto flex h-full items-center justify-between px-6 text-purple-600">
        <button
          className="focus:shadow-outline-purple -ml-1 mr-5 rounded-md p-1 focus:outline-none lg:hidden"
          aria-label="Menu"
        >
          <Bars3Icon className="h-4 w-4" aria-hidden="true" />
        </button>

        <div className="flex flex-1 justify-center">
          <div className="relative mr-6 w-full max-w-xl focus-within:text-purple-500">
            <div className="absolute inset-y-0 flex items-center pl-2">
              <MagnifyingGlassIcon className="h-4 w-4" aria-hidden="true" />
            </div>
            <input
              className="text w-full rounded-lg bg-gray-100 py-2 pl-8 text-gray-700 outline-purple-500"
              placeholder="Search something..."
              aria-label="Search"
            />
          </div>
        </div>

        <ul className="flex flex-shrink-0 items-center space-x-6">
          <li className="relative">
            <button
              onClick={toggleDropdown}
              className="focus:shadow-outline-purple rounded-md focus:outline-none"
              aria-label="Toggle dropdown"
            >
              <img
                className="h-10 w-10 rounded-full border-2 border-purple-400 object-cover"
                src="https://picsum.photos/150"
                alt="User avatar"
              />
            </button>
            {isDropdownOpen && (
              <ul className="absolute right-0 mt-2 w-48 rounded-lg bg-gray-50 text-gray-700 shadow-lg">
                <li className="cursor-pointer p-2 text-sm hover:bg-gray-100">
                  Profile
                </li>
                <li className="cursor-pointer p-2 text-sm hover:bg-gray-100">
                  Settings
                </li>
                <li className="cursor-pointer p-2 text-sm hover:bg-gray-100">
                  Logout
                </li>
              </ul>
            )}
          </li>
        </ul>
      </div>
    </header>
  );
};

export default Header;

// web/src/lib/components/layouts/Header.svelte
<script lang="ts">
	import { LogOut, Menu } from "lucide-svelte";

	let show: boolean = $state(false);
	let menu: HTMLElement | null = null;

	$effect(() => {
		const handleOutsideClick = (event: MouseEvent): void => {
			if (show && !menu?.contains(event.target as Node)) {
				show = false;
			}
		};

		const handleEscape = (event: KeyboardEvent): void => {
			if (show && event.key === "Escape") {
				show = false;
			}
		};

		document.addEventListener("click", handleOutsideClick, false);
		document.addEventListener("keyup", handleEscape, false);

		return () => {
			document.removeEventListener("click", handleOutsideClick, false);
			document.removeEventListener("keyup", handleEscape, false);
		};
	});

	let { toggleSidebar } = $props();
</script>

<header class="sticky top-0 z-10 border-b border-gray-200 bg-white">
	<div class="mx-auto px-4">
		<div class="flex h-16 items-center justify-between">
			<!--  -->
			<div class="flex-1">
				<Menu class="size-7 lg:hidden" onclick={toggleSidebar} />
				<a class="hidden text-teal-600 lg:block" href="/">
					<span class="sr-only">Home</span>
					<svg class="h-8" viewBox="0 0 28 24" fill="none" xmlns="http://www.w3.org/2000/svg">
						<path
							d="M0.41 10.3847C1.14777 7.4194 2.85643 4.7861 5.2639 2.90424C7.6714 1.02234 10.6393 0 13.695 0C16.7507 0 19.7186 1.02234 22.1261 2.90424C24.5336 4.7861 26.2422 7.4194 26.98 10.3847H25.78C23.7557 10.3549 21.7729 10.9599 20.11 12.1147C20.014 12.1842 19.9138 12.2477 19.81 12.3047H19.67C19.5662 12.2477 19.466 12.1842 19.37 12.1147C17.6924 10.9866 15.7166 10.3841 13.695 10.3841C11.6734 10.3841 9.6976 10.9866 8.02 12.1147C7.924 12.1842 7.8238 12.2477 7.72 12.3047H7.58C7.4762 12.2477 7.376 12.1842 7.28 12.1147C5.6171 10.9599 3.6343 10.3549 1.61 10.3847H0.41ZM23.62 16.6547C24.236 16.175 24.9995 15.924 25.78 15.9447H27.39V12.7347H25.78C24.4052 12.7181 23.0619 13.146 21.95 13.9547C21.3243 14.416 20.5674 14.6649 19.79 14.6649C19.0126 14.6649 18.2557 14.416 17.63 13.9547C16.4899 13.1611 15.1341 12.7356 13.745 12.7356C12.3559 12.7356 11.0001 13.1611 9.86 13.9547C9.2343 14.416 8.4774 14.6649 7.7 14.6649C6.9226 14.6649 6.1657 14.416 5.54 13.9547C4.4144 13.1356 3.0518 12.7072 1.66 12.7347H0V15.9447H1.61C2.39051 15.924 3.154 16.175 3.77 16.6547C4.908 17.4489 6.2623 17.8747 7.65 17.8747C9.0377 17.8747 10.392 17.4489 11.53 16.6547C12.1468 16.1765 12.9097 15.9257 13.69 15.9447C14.4708 15.9223 15.2348 16.1735 15.85 16.6547C16.9901 17.4484 18.3459 17.8738 19.735 17.8738C21.1241 17.8738 22.4799 17.4484 23.62 16.6547ZM23.62 22.3947C24.236 21.915 24.9995 21.664 25.78 21.6847H27.39V18.4747H25.78C24.4052 18.4581 23.0619 18.886 21.95 19.6947C21.3243 20.156 20.5674 20.4049 19.79 20.4049C19.0126 20.4049 18.2557 20.156 17.63 19.6947C16.4899 18.9011 15.1341 18.4757 13.745 18.4757C12.3559 18.4757 11.0001 18.9011 9.86 19.6947C9.2343 20.156 8.4774 20.4049 7.7 20.4049C6.9226 20.4049 6.1657 20.156 5.54 19.6947C4.4144 18.8757 3.0518 18.4472 1.66 18.4747H0V21.6847H1.61C2.39051 21.664 3.154 21.915 3.77 22.3947C4.908 23.1889 6.2623 23.6147 7.65 23.6147C9.0377 23.6147 10.392 23.1889 11.53 22.3947C12.1468 21.9165 12.9097 21.6657 13.69 21.6847C14.4708 21.6623 15.2348 21.9135 15.85 22.3947C16.9901 23.1884 18.3459 23.6138 19.735 23.6138C21.1241 23.6138 22.4799 23.1884 23.62 22.3947Z"
							fill="currentColor"
						/>
					</svg>
				</a>
			</div>

			<!--  -->
			<div class="flex">
				<div class="relative" bind:this={menu}>
					<button
						onclick={() => (show = !show)}
						type="button"
						class="border-3 overflow-hidden rounded-full border-gray-300 shadow-inner"
					>
						<span class="sr-only">Toggle dashboard menu</span>
						<img src="/profile.avif" alt="profile user" class="size-10 object-cover" />
					</button>

					{#if show}
						<div
							class="absolute end-0 z-10 mt-2 w-56 divide-y divide-gray-100 rounded-md border border-gray-200 bg-white shadow"
							role="menu"
						>
							<div class="p-2">
								<a
									href="/"
									class="block rounded-lg px-4 py-2 text-sm text-gray-500 hover:bg-gray-100 hover:text-gray-700"
									role="menuitem"
								>
									My profile
								</a>

								<a
									href="/"
									class="block rounded-lg px-4 py-2 text-sm text-gray-500 hover:bg-gray-100 hover:text-gray-700"
									role="menuitem"
								>
									Billing summary
								</a>

								<a
									href="/"
									class="block rounded-lg px-4 py-2 text-sm text-gray-500 hover:bg-gray-100 hover:text-gray-700"
									role="menuitem"
								>
									Team settings
								</a>
							</div>

							<div class="p-2">
								<button
									type="button"
									class="flex w-full cursor-pointer items-center gap-2 rounded-lg px-4 py-2 text-sm text-red-700 hover:bg-red-50"
									role="menuitem"
								>
									<LogOut class="size-4" />

									Logout
								</button>
							</div>
						</div>
					{/if}
				</div>
			</div>
		</div>
	</div>
</header>
