// web/src/routes/(auth)/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { onMount } from 'svelte';

	let email = '';
	let password = '';
	let rememberMe = false;
	let isLoading = false;

	onMount(() => {
		const savedEmail = localStorage.getItem('rememberedEmail');
		if (savedEmail) {
			email = savedEmail;
			rememberMe = true;
		}
	});

	async function handleSubmit(_: SubmitEvent) {
		isLoading = true;

		setTimeout(() => {
			if (rememberMe) localStorage.setItem('rememberedEmail', email);
			else localStorage.removeItem('rememberedEmail');

			isLoading = false;
			email = '';
			password = '';
			rememberMe = false;
			goto('/dashboard');
		}, 1000);
	}
</script>

<h2 class="mb-6 text-center text-2xl font-bold text-gray-800">Sign In</h2>

<form class="space-y-4" on:submit|preventDefault={handleSubmit}>
	<div>
		<label for="email" class="mb-1 block text-sm font-medium text-gray-700">Email</label>
		<input
			type="email"
			id="email"
			bind:value={email}
			class="w-full rounded-lg border border-gray-300 px-4 py-2 transition-all outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
			placeholder="your@email.com"
		/>
	</div>

	<div>
		<label for="password" class="mb-1 block text-sm font-medium text-gray-700">Password</label>
		<input
			type="password"
			id="password"
			bind:value={password}
			class="w-full rounded-lg border border-gray-300 px-4 py-2 transition-all outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
			placeholder="••••••••"
		/>
	</div>

	<div class="flex items-center justify-between">
		<label class="flex items-center">
			<input
				type="checkbox"
				bind:checked={rememberMe}
				class="rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
			/>
			<span class="ml-2 text-sm text-gray-600">Remember me</span>
		</label>
		<a href="/forgot-password" class="text-sm text-indigo-600 hover:text-indigo-500">
			Forgot password?
		</a>
	</div>

	<button
		type="submit"
		disabled={isLoading}
		class="w-full rounded-lg py-2.5 font-medium text-white transition-colors {isLoading
			? 'cursor-not-allowed bg-indigo-400'
			: 'bg-indigo-600 hover:bg-indigo-700'}"
	>
		{isLoading ? 'Loading...' : 'Sign In'}
	</button>
</form>

<div class="mt-6 text-center text-sm text-gray-600">
	Don't have an account? <a
		href="/register"
		class="font-medium text-indigo-600 hover:text-indigo-500"
	>
		Sign Up
	</a>
</div>

// web/src/pages/Login.tsx
import { Link } from "react-router";
import { useState, useEffect } from "react";

export default function Login() {
  const [formData, setFormData] = useState({
    email: "",
    password: "",
    rememberMe: false,
  });
  const [isLoading, setIsLoading] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value, type, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }));
  };

  useEffect(() => {
    const savedEmail = localStorage.getItem("rememberedEmail");
    if (savedEmail) {
      setFormData((prev) => ({ ...prev, email: savedEmail, rememberMe: true }));
    }
  }, []);

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    setIsLoading(true);

    setTimeout(function () {
      // Simulating API call
      if (formData.rememberMe) {
        localStorage.setItem("rememberedEmail", formData.email); // Save email
      } else {
        localStorage.removeItem("rememberedEmail"); // Remove email if "Remember Me" is unchecked
      }

      setIsLoading(false);
      setFormData({ email: "", password: "", rememberMe: false });
    }, 1000);

    // await api call to send reset password link
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100 p-4">
      <div className="w-full max-w-md rounded-xl bg-white p-8 shadow-lg">
        <h2 className="mb-6 text-center text-2xl font-bold text-gray-900">
          Sign In
        </h2>

        <form className="space-y-4" onSubmit={handleSubmit}>
          <div>
            <label
              htmlFor="email"
              className="mb-1 block text-sm font-medium text-gray-700"
            >
              Email
            </label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className="w-full rounded-lg border border-gray-300 px-4 py-2 outline-none transition-all focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
              placeholder="your@email.com"
            />
          </div>

          <div>
            <label
              htmlFor="password"
              className="mb-1 block text-sm font-medium text-gray-700"
            >
              Password
            </label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              className="w-full rounded-lg border border-gray-300 px-4 py-2 outline-none transition-all focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
              placeholder="••••••••"
            />
          </div>

          <div className="flex items-center justify-between">
            <label className="flex items-center">
              <input
                type="checkbox"
                name="rememberMe"
                checked={formData.rememberMe}
                onChange={handleChange}
                className="rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
              />
              <span className="ml-2 text-sm text-gray-600">Remember me</span>
            </label>
            <Link
              to="/forgot-password"
              className="text-sm text-indigo-600 hover:text-indigo-500"
            >
              Forgot password?
            </Link>
          </div>

          <button
            type="submit"
            disabled={isLoading} // Disable button during loading
            className={`w-full rounded-lg py-2.5 font-medium text-white transition-colors ${
              isLoading
                ? "cursor-not-allowed bg-indigo-400"
                : "bg-indigo-600 hover:bg-indigo-700"
            }`}
          >
            {isLoading ? "Loading..." : "Sign In"}
          </button>
        </form>

        <div className="mt-6 text-center text-sm text-gray-600">
          Don't have an account?
          <Link
            to="/register"
            className="font-medium text-indigo-600 hover:text-indigo-500"
          >
            Sign up
          </Link>
        </div>
      </div>
    </div>
  );
}
