// web/src/routes/(auth)/register/+page.svelte
<script lang="ts">
	let formData = { email: '', password: '' };
	let isLoading = false;

	async function handleSubmit(_: SubmitEvent) {
		isLoading = true;

		setTimeout(() => {
			isLoading = false;
			formData = { email: '', password: '' }; // Reset form
		}, 1000);
	}
</script>

<h2 class="mb-6 text-center text-2xl font-bold text-gray-800">Sign Up</h2>
<form class="space-y-4" on:submit|preventDefault={handleSubmit}>
	<div>
		<label for="email" class="mb-1 block text-sm font-medium text-gray-700">Email</label>
		<input
			type="email"
			id="email"
			bind:value={formData.email}
			class="w-full rounded-lg border border-gray-300 px-4 py-2 transition-all outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
			placeholder="your@email.com"
		/>
	</div>

	<div>
		<label for="password" class="mb-1 block text-sm font-medium text-gray-700">Password</label>
		<input
			type="password"
			id="password"
			bind:value={formData.password}
			class="w-full rounded-lg border border-gray-300 px-4 py-2 transition-all outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
			placeholder="••••••••"
		/>
	</div>

	<p class="text-xs text-gray-600">By clicking Sign Up, you agree to our Terms and Conditions.</p>

	<button
		type="submit"
		disabled={isLoading}
		class="w-full rounded-lg py-2.5 font-medium text-white transition-colors {isLoading
			? 'cursor-not-allowed bg-indigo-400'
			: 'bg-indigo-600 hover:bg-indigo-700'}"
	>
		{isLoading ? 'Loading...' : 'Sign Up'}
	</button>
</form>

<div class="mt-6 text-center text-sm text-gray-600">
	Have an account? <a href="/login" class="font-medium text-indigo-600 hover:text-indigo-500">
		Sign In
	</a>
</div>

// web/src/pages/Register.tsx
import { Link } from "react-router";
import { useState } from "react";

export default function Register() {
  const [formData, setFormData] = useState({
    email: "",
    password: "",
  });
  const [isLoading, setIsLoading] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    setIsLoading(true);

    setTimeout(function () {
      // Simulating API call

      setIsLoading(false);
      setFormData({ email: "", password: "" });
    }, 1000);

    // await api call to send reset password link
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100 p-4">
      <div className="w-full max-w-md rounded-xl bg-white p-8 shadow-lg">
        <h2 className="mb-6 text-center text-2xl font-bold text-gray-900">
          Sign Up
        </h2>

        <form className="space-y-4" onSubmit={handleSubmit}>
          <div>
            <label
              htmlFor="email"
              className="mb-1 block text-sm font-medium text-gray-700"
            >
              Email
            </label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className="w-full rounded-lg border border-gray-300 px-4 py-2 outline-none transition-all focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
              placeholder="your@email.com"
            />
          </div>

          <div>
            <label
              htmlFor="password"
              className="mb-1 block text-sm font-medium text-gray-700"
            >
              Password
            </label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              className="w-full rounded-lg border border-gray-300 px-4 py-2 outline-none transition-all focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
              placeholder="••••••••"
            />
          </div>

          <p className="text-xs text-gray-600">
            By clicking Sign Up, you agree to our Terms and Conditions.
          </p>

          <button
            type="submit"
            disabled={isLoading} // Disable button during loading
            className={`w-full rounded-lg py-2.5 font-medium text-white transition-colors ${
              isLoading
                ? "cursor-not-allowed bg-indigo-400"
                : "bg-indigo-600 hover:bg-indigo-700"
            }`}
          >
            {isLoading ? "Loading..." : "Sign Up"}
          </button>
        </form>

        <div className="mt-6 text-center text-sm text-gray-600">
          Have an account?
          <Link
            to="/login"
            className="font-medium text-indigo-600 hover:text-indigo-500"
          >
            Sign in
          </Link>
        </div>
      </div>
    </div>
  );
}
