// web/src/components/Header.tsx
import  { useState } from "react";
import { MagnifyingGlassIcon, Bars3Icon } from "@heroicons/react/24/solid";

const Header: React.FC = () => {
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);

  const toggleDropdown = () => {
    setIsDropdownOpen((prev) => !prev);
  };

  return (
    <header className="shadow-bottom z-20 bg-white py-4">
      <div className="container mx-auto flex h-full items-center justify-between px-6 text-purple-600">
        <button
          className="focus:shadow-outline-purple -ml-1 mr-5 rounded-md p-1 focus:outline-none lg:hidden"
          aria-label="Menu"
        >
          <Bars3Icon className="h-4 w-4" aria-hidden="true" />
        </button>

        <div className="flex flex-1 justify-center">
          <div className="relative mr-6 w-full max-w-xl focus-within:text-purple-500">
            <div className="absolute inset-y-0 flex items-center pl-2">
              <MagnifyingGlassIcon className="h-4 w-4" aria-hidden="true" />
            </div>
            <input
              className="text w-full rounded-lg bg-gray-100 py-3 pl-8 text-gray-700 outline-purple-500"
              placeholder="Search something..."
              aria-label="Search"
            />
          </div>
        </div>

        <ul className="flex flex-shrink-0 items-center space-x-6">
          <li className="relative">
            <button
              onClick={toggleDropdown}
              className="focus:shadow-outline-purple rounded-md focus:outline-none "
              aria-label="Toggle dropdown"
            >
              <img
                className="h-10 w-10 rounded-full object-cover border-2 border-purple-400"
                src="https://picsum.photos/150"
                alt="User avatar"
              />
            </button>
            {isDropdownOpen && (
              <ul className="absolute right-0 mt-2 w-48 rounded-lg bg-gray-50 text-gray-700 shadow-lg">
                <li className="cursor-pointer p-2 text-sm hover:bg-gray-100">
                  Profile
                </li>
                <li className="cursor-pointer p-2 text-sm hover:bg-gray-100">
                  Settings
                </li>
                <li className="cursor-pointer p-2 text-sm hover:bg-gray-100">
                  Logout
                </li>
              </ul>
            )}
          </li>
        </ul>
      </div>
    </header>
  );
};

export default Header;

// web/src/lib/components/Header.svelte
<script lang="ts">
	import { Menu } from 'lucide-svelte';
	import { menus } from '$lib';
	import { page } from '$app/state';

	let title: string = $state('');
	$effect(() => {
		title = menus.find((menu) => menu.link === page.url.pathname)?.title || '';
	});

	let { handleMenuClick }: { handleMenuClick: () => void } = $props();
</script>

<header class="fixed z-50 w-full select-none border-b border-gray-200 bg-white">
	<div class="mx-auto px-4">
		<div class="flex h-16 items-center justify-between">
			<div class="mr-auto flex">
				<Menu class="h-7 w-7 hover:cursor-pointer" onclick={handleMenuClick} />
				<div class="ml-2 flex flex-shrink-0 items-center space-x-2">
					<img class="hidden h-7 w-7 md:block" src="/logo.svg" alt="" />
					<h2 class="text-xl font-bold">{title}</h2>
				</div>
			</div>
			<div class="flex items-center justify-end space-x-6 sm:ml-5">
				<button
					class="flex max-w-xs items-center rounded-full bg-gray-100 hover:cursor-pointer focus:outline-none"
				>
					<img
						class="bg-secondary h-8 w-8 rounded-full object-cover"
						src="https://api.dicebear.com/7.x/croodles/png?seed=Shivam"
						alt=""
					/>
					<span class="ml-2 mr-3 hidden text-sm font-medium md:block"> Username </span>
				</button>
			</div>
		</div>
	</div>
</header>
